export { default as Welcome } from './Welcome'
export { default as Capture } from './Capture'
export { default as Loading } from './Loading'
export { default as Player } from './Player'
export { default as Fail } from './Fail'
